name			    = "Kommandokräfte Crusader - Utilities";					// Name of your mod
author			    = "Miss Heda";				                                // Affects Arma 3 Launcher, when the mod are loaded as local
logo			    = "LogoLow.paa";			                                // Logo displayed in the main menu
logoOver		    = "LogoLow.paa";	                                        // When the mouse is over, in the main menu
tooltip			    = "Kommandokräfte Crusader - Utilities";
tooltipOwned	    = "Kommandokräfte Crusader - Utilities";				    // Tool tip displayed when the mouse is left over, in the main menu
picture			    = "LogoHigh.paa";		                                    // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName		    = "GitHub";
action			    = "https://github.com/MissHeda/Crusader-Utilities";			// Website URL, that can be accessed from the expansions menu
overview		    = "Kommandokräfte Crusader - Utilities";	                // Supports structured text
hideName		    = 0;						                                // Hide the extension name
hidePicture		    = 0;						                                // Hide the extension menu
dlcColor[]		    = { 0.23, 0.39, 0.30, 1 };	                                // Color used for DLC stripes and backgrounds (RGBA)
logoSmall		    = "LogoLow.paa";		                                    // Display in creative lists, next to the entities added by the mod